CREATE TABLE UC_CAR (
	NUM NUMBER(38,0) NOT NULL,
	SELLER VARCHAR2(20) NOT NULL,
    COP_NAME VARCHAR2(20) NOT NULL,
    BR_NAME VARCHAR2(20) NOT NULL,
    CAR_NAME VARCHAR2(20) NOT NULL,
    PRICE NUMBER(20,0) NOT NULL,
    MILEAGE NUMBER(10,0) NOT NULL,
    MODEL_YEAR NUMBER(10,0) NOT NULL,
    FUEL_TYPE VARCHAR2(20) NOT NULL,
    COLOR VARCHAR2(20) NOT NULL,
    REGION VARCHAR2(20) NOT NULL,
    NUMBER_P NUMBER(10,0) NOT NULL,    
    OWNER VARCHAR2(20) NOT NULL,
    UC_TEXT VARCHAR2(40),
    REGDATE DATE DEFAULT SYSDATE,
    UPDATEDATE DATE DEFAULT SYSDATE,
    PRIMARY KEY (NUM)
 );

CREATE SEQUENCE SEQ_NUM
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1
       MAXVALUE 99999
       CYCLE
       ORDER;